version: '3.8'

services:
  s_helloworld:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: c_helloworld
    ports:
      - "8085:8085"
    restart: on-failure
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8085/actuator/health"]
      interval: 5s
      timeout: 30s
      start_period: 10s
      retries: 3
